version: '3.8'

services:
  backend:
    restart: on-failure
    build: api-svc
    depends_on:
      - db
    env_file:
      - api-svc/.env
    ports:
      - "8080:8080"
    command: run-server # migrates-up migrates-down run-server

  db:
    restart: on-failure
    image: postgres
    env_file:
      - api-svc/database.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: on-failure
    ports:
      - "80:80"
    env_file:
      - api-svc/pgadmin.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-data:
  pgadmin-data:
